/**
 * Catalog of realistic Portuguese demo fixtures for ZRIK Demo Mode.
 */
export const VEHICLE_CLASSES = [
  {
    id: "vc_comfort",
    code: "COMFORT",
    namePt: "Comfort",
    nameEn: "Comfort",
    descriptionPt: "Veículos executivos standard até 4 passageiros",
    descriptionEn: "Standard executive vehicles up to 4 passengers",
    minPassengers: 1,
    maxPassengers: 4,
    maxLuggage: 3,
    iconKey: "comfort",
    sortOrder: 10,
  },
  {
    id: "vc_premium",
    code: "PREMIUM",
    namePt: "Premium",
    nameEn: "Premium",
    descriptionPt: "Veículos executivos de luxo até 4 passageiros",
    descriptionEn: "Luxury executive vehicles up to 4 passengers",
    minPassengers: 1,
    maxPassengers: 4,
    maxLuggage: 4,
    iconKey: "premium",
    sortOrder: 20,
  },
  {
    id: "vc_van",
    code: "VAN",
    namePt: "Van",
    nameEn: "Van",
    descriptionPt: "Vans executivas para famílias e grupos até 8 passageiros",
    descriptionEn: "Executive vans for families and groups up to 8 passengers",
    minPassengers: 1,
    maxPassengers: 8,
    maxLuggage: 8,
    iconKey: "van",
    sortOrder: 30,
  },
] as const;

/** Legacy codes soft-deactivated on seed (no Bus/Minibus/old taxonomy). */
export const RETIRED_VEHICLE_CLASS_CODES = [
  "SEDAN",
  "EXECUTIVE",
  "LUXURY",
  "MINIBUS",
  "BUS",
] as const;


export const DRIVER_PHOTOS = [
  "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop",
  "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop",
  "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop",
  "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop",
  "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop",
  "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=400&fit=crop",
  "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop",
  "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=400&fit=crop",
];

export const CUSTOMER_PHOTOS = [
  "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop",
  "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop",
  "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop",
];

export type DemoDriverSpec = {
  email: string;
  name: string;
  phone: string;
  locale: string;
  bio: string;
  years: number;
  languages: string[];
  status: "ACTIVE" | "PENDING_VERIFICATION" | "SUSPENDED" | "REJECTED";
  onboardingStatus:
    | "APPROVED"
    | "UNDER_REVIEW"
    | "NEEDS_INFO"
    | "SUBMITTED"
    | "REJECTED"
    | "IN_PROGRESS";
  vehicle: {
    make: string;
    model: string;
    year: number;
    color: string;
    plate: string;
    seats: number;
    luggage: number;
    classId: string;
  };
};

export const DEMO_DRIVERS: DemoDriverSpec[] = [
  {
    email: "motorista@movio.app",
    name: "Carlos Motorista",
    phone: "+351920000001",
    locale: "pt",
    bio: "Executive chauffeur with 8 years of airport transfer experience across Portugal.",
    years: 8,
    languages: ["pt", "en", "es"],
    status: "ACTIVE",
    onboardingStatus: "APPROVED",
    vehicle: {
      make: "Mercedes-Benz",
      model: "E-Class",
      year: 2023,
      color: "Black",
      plate: "AA-00-MV",
      seats: 4,
      luggage: 3,
      classId: "vc_premium",
    },
  },
  {
    email: "motorista2@movio.app",
    name: "Rita Condutora",
    phone: "+351920000002",
    locale: "en",
    bio: "Specialist in Lisbon–Algarve private transfers and group vans.",
    years: 5,
    languages: ["pt", "en"],
    status: "ACTIVE",
    onboardingStatus: "APPROVED",
    vehicle: {
      make: "Volkswagen",
      model: "Caravelle",
      year: 2022,
      color: "Silver",
      plate: "BB-11-MV",
      seats: 7,
      luggage: 7,
      classId: "vc_van",
    },
  },
  {
    email: "pendente@movio.app",
    name: "João Pendente",
    phone: "+351920000003",
    locale: "pt",
    bio: "Lisbon-based chauffeur seeking platform approval. Airport transfers and hotel runs.",
    years: 3,
    languages: ["pt", "en"],
    status: "PENDING_VERIFICATION",
    onboardingStatus: "UNDER_REVIEW",
    vehicle: {
      make: "BMW",
      model: "5 Series",
      year: 2021,
      color: "Blue",
      plate: "CC-22-MV",
      seats: 4,
      luggage: 2,
      classId: "vc_comfort",
    },
  },
  {
    email: "driver03@movio.app",
    name: "Miguel Santos",
    phone: "+351920000004",
    locale: "pt",
    bio: "Porto and Lisbon shuttle specialist. Quiet rides, always on time.",
    years: 6,
    languages: ["pt", "en", "fr"],
    status: "ACTIVE",
    onboardingStatus: "APPROVED",
    vehicle: {
      make: "Audi",
      model: "A6",
      year: 2022,
      color: "Grey",
      plate: "DD-33-MV",
      seats: 4,
      luggage: 3,
      classId: "vc_premium",
    },
  },
  {
    email: "driver04@movio.app",
    name: "Sofia Ferreira",
    phone: "+351920000005",
    locale: "pt",
    bio: "Female chauffeur focused on safety and comfort for solo travellers.",
    years: 4,
    languages: ["pt", "en"],
    status: "ACTIVE",
    onboardingStatus: "APPROVED",
    vehicle: {
      make: "Tesla",
      model: "Model 3",
      year: 2024,
      color: "White",
      plate: "EE-44-MV",
      seats: 4,
      luggage: 2,
      classId: "vc_comfort",
    },
  },
  {
    email: "driver05@movio.app",
    name: "Bruno Almeida",
    phone: "+351920000006",
    locale: "pt",
    bio: "Luxury transfers for corporate clients and hotel concierges.",
    years: 10,
    languages: ["pt", "en", "es"],
    status: "ACTIVE",
    onboardingStatus: "APPROVED",
    vehicle: {
      make: "Mercedes-Benz",
      model: "S-Class",
      year: 2023,
      color: "Black",
      plate: "FF-55-MV",
      seats: 4,
      luggage: 3,
      classId: "vc_premium",
    },
  },
  {
    email: "driver06@movio.app",
    name: "Inês Costa",
    phone: "+351920000007",
    locale: "pt",
    bio: "Family-friendly vans with child seats on request.",
    years: 7,
    languages: ["pt", "en"],
    status: "ACTIVE",
    onboardingStatus: "APPROVED",
    vehicle: {
      make: "Mercedes-Benz",
      model: "V-Class",
      year: 2021,
      color: "Silver",
      plate: "GG-66-MV",
      seats: 7,
      luggage: 6,
      classId: "vc_van",
    },
  },
  {
    email: "driver07@movio.app",
    name: "Pedro Nunes",
    phone: "+351920000008",
    locale: "pt",
    bio: "Night flights and early morning pickups — available 24/7.",
    years: 9,
    languages: ["pt", "en"],
    status: "ACTIVE",
    onboardingStatus: "APPROVED",
    vehicle: {
      make: "Skoda",
      model: "Superb",
      year: 2020,
      color: "Black",
      plate: "HH-77-MV",
      seats: 4,
      luggage: 3,
      classId: "vc_premium",
    },
  },
  {
    email: "driver08@movio.app",
    name: "Helena Rocha",
    phone: "+351920000009",
    locale: "en",
    bio: "English-speaking driver for Cascais and Estoril hotel runs.",
    years: 5,
    languages: ["en", "pt"],
    status: "ACTIVE",
    onboardingStatus: "APPROVED",
    vehicle: {
      make: "BMW",
      model: "3 Series",
      year: 2022,
      color: "Blue",
      plate: "II-88-MV",
      seats: 4,
      luggage: 2,
      classId: "vc_comfort",
    },
  },
  {
    email: "driver09@movio.app",
    name: "Tiago Mendes",
    phone: "+351920000010",
    locale: "pt",
    bio: "Group transfers and event logistics around Greater Lisbon.",
    years: 11,
    languages: ["pt", "en", "es"],
    status: "ACTIVE",
    onboardingStatus: "APPROVED",
    vehicle: {
      make: "Ford",
      model: "Tourneo Custom",
      year: 2021,
      color: "White",
      plate: "JJ-99-MV",
      seats: 8,
      luggage: 8,
      classId: "vc_van",
    },
  },
  {
    email: "driver10@movio.app",
    name: "Carla Dias",
    phone: "+351920000011",
    locale: "pt",
    bio: "Smooth airport meets with flight tracking and name board.",
    years: 6,
    languages: ["pt", "en", "fr"],
    status: "ACTIVE",
    onboardingStatus: "APPROVED",
    vehicle: {
      make: "Volvo",
      model: "S90",
      year: 2023,
      color: "Grey",
      plate: "KK-10-MV",
      seats: 4,
      luggage: 3,
      classId: "vc_premium",
    },
  },
  {
    email: "driver11@movio.app",
    name: "André Lopes",
    phone: "+351920000012",
    locale: "pt",
    bio: "Reliable sedan for city hops and station pickups.",
    years: 4,
    languages: ["pt"],
    status: "ACTIVE",
    onboardingStatus: "APPROVED",
    vehicle: {
      make: "Toyota",
      model: "Camry",
      year: 2022,
      color: "White",
      plate: "LL-11-MV",
      seats: 4,
      luggage: 2,
      classId: "vc_comfort",
    },
  },
  {
    email: "driver12@movio.app",
    name: "Marta Pinto",
    phone: "+351920000013",
    locale: "pt",
    bio: "Premium EV chauffeur — silent cabin, charged and ready.",
    years: 3,
    languages: ["pt", "en"],
    status: "ACTIVE",
    onboardingStatus: "APPROVED",
    vehicle: {
      make: "Tesla",
      model: "Model S",
      year: 2024,
      color: "Red",
      plate: "MM-12-MV",
      seats: 4,
      luggage: 2,
      classId: "vc_premium",
    },
  },
  {
    email: "driver13@movio.app",
    name: "Ricardo Gomes",
    phone: "+351920000014",
    locale: "pt",
    bio: "Sintra and wine-country day trips with flexible waits.",
    years: 8,
    languages: ["pt", "en", "de"],
    status: "ACTIVE",
    onboardingStatus: "APPROVED",
    vehicle: {
      make: "Mercedes-Benz",
      model: "E-Class",
      year: 2021,
      color: "Silver",
      plate: "NN-13-MV",
      seats: 4,
      luggage: 3,
      classId: "vc_premium",
    },
  },
  {
    email: "driver14@movio.app",
    name: "Patrícia Sousa",
    phone: "+351920000015",
    locale: "pt",
    bio: "Cruise port and hotel transfers in Lisbon and Setúbal.",
    years: 5,
    languages: ["pt", "en", "es"],
    status: "ACTIVE",
    onboardingStatus: "APPROVED",
    vehicle: {
      make: "Peugeot",
      model: "508",
      year: 2020,
      color: "Black",
      plate: "OO-14-MV",
      seats: 4,
      luggage: 2,
      classId: "vc_comfort",
    },
  },
  {
    email: "driver15@movio.app",
    name: "Nuno Carvalho",
    phone: "+351920000016",
    locale: "pt",
    bio: "Corporate accounts and recurring weekly routes.",
    years: 12,
    languages: ["pt", "en"],
    status: "ACTIVE",
    onboardingStatus: "APPROVED",
    vehicle: {
      make: "Audi",
      model: "A8",
      year: 2022,
      color: "Black",
      plate: "PP-15-MV",
      seats: 4,
      luggage: 3,
      classId: "vc_premium",
    },
  },
  {
    email: "driver16@movio.app",
    name: "Beatriz Ramos",
    phone: "+351920000017",
    locale: "en",
    bio: "Friendly van driver for families arriving with lots of luggage.",
    years: 4,
    languages: ["en", "pt"],
    status: "ACTIVE",
    onboardingStatus: "APPROVED",
    vehicle: {
      make: "Volkswagen",
      model: "Multivan",
      year: 2023,
      color: "Blue",
      plate: "QQ-16-MV",
      seats: 7,
      luggage: 7,
      classId: "vc_van",
    },
  },
  {
    email: "driver17@movio.app",
    name: "Fábio Teixeira",
    phone: "+351920000018",
    locale: "pt",
    bio: "Submitted for review — documents uploaded, awaiting AI + admin.",
    years: 2,
    languages: ["pt"],
    status: "PENDING_VERIFICATION",
    onboardingStatus: "SUBMITTED",
    vehicle: {
      make: "Renault",
      model: "Talisman",
      year: 2019,
      color: "Grey",
      plate: "RR-17-MV",
      seats: 4,
      luggage: 2,
      classId: "vc_comfort",
    },
  },
  {
    email: "driver18@movio.app",
    name: "Diana Moreira",
    phone: "+351920000019",
    locale: "pt",
    bio: "Needs updated insurance certificate before approval.",
    years: 3,
    languages: ["pt", "en"],
    status: "PENDING_VERIFICATION",
    onboardingStatus: "NEEDS_INFO",
    vehicle: {
      make: "Opel",
      model: "Insignia",
      year: 2020,
      color: "White",
      plate: "SS-18-MV",
      seats: 4,
      luggage: 2,
      classId: "vc_comfort",
    },
  },
  {
    email: "driver19@movio.app",
    name: "Hugo Barbosa",
    phone: "+351920000020",
    locale: "pt",
    bio: "Previously suspended after repeated late cancellations.",
    years: 2,
    languages: ["pt"],
    status: "SUSPENDED",
    onboardingStatus: "REJECTED",
    vehicle: {
      make: "Seat",
      model: "Leon",
      year: 2018,
      color: "Red",
      plate: "TT-19-MV",
      seats: 4,
      luggage: 2,
      classId: "vc_comfort",
    },
  },
];

export const DEMO_CUSTOMERS = [
  { email: "cliente@movio.app", name: "Ana Cliente", phone: "+351910000001", locale: "pt" },
  { email: "cliente2@movio.app", name: "Pedro Oliveira", phone: "+351910000002", locale: "pt" },
  { email: "cliente3@movio.app", name: "Maria Silva", phone: "+351910000003", locale: "pt" },
  { email: "cliente4@movio.app", name: "John Mercer", phone: "+351910000004", locale: "en" },
  { email: "cliente5@movio.app", name: "Laura Chen", phone: "+351910000005", locale: "en" },
  { email: "cliente6@movio.app", name: "Gonçalo Ribeiro", phone: "+351910000006", locale: "pt" },
  { email: "cliente7@movio.app", name: "Sophie Martin", phone: "+351910000007", locale: "en" },
  { email: "cliente8@movio.app", name: "Joana Martins", phone: "+351910000008", locale: "pt" },
  { email: "cliente9@movio.app", name: "Tom Hughes", phone: "+351910000009", locale: "en" },
  { email: "cliente10@movio.app", name: "Catarina Lopes", phone: "+351910000010", locale: "pt" },
  { email: "cliente11@movio.app", name: "Eduardo Freitas", phone: "+351910000011", locale: "pt" },
  { email: "cliente12@movio.app", name: "Amelia Brown", phone: "+351910000012", locale: "en" },
];

export const ROUTES: {
  pickup: string;
  dropoff: string;
  plat: number;
  plng: number;
  dlat: number;
  dlng: number;
  classId: string;
  basePrice: number;
}[] = [
  {
    pickup: "Aeroporto de Lisboa (LIS), Lisboa",
    dropoff: "Praça do Comércio, Lisboa",
    plat: 38.7756,
    plng: -9.1354,
    dlat: 38.7075,
    dlng: -9.1364,
    classId: "vc_premium",
    basePrice: 4200,
  },
  {
    pickup: "Aeroporto de Lisboa (LIS), Lisboa",
    dropoff: "Cascais Marina, Cascais",
    plat: 38.7756,
    plng: -9.1354,
    dlat: 38.6969,
    dlng: -9.4205,
    classId: "vc_premium",
    basePrice: 6500,
  },
  {
    pickup: "Estação do Oriente, Lisboa",
    dropoff: "Sintra National Palace, Sintra",
    plat: 38.7679,
    plng: -9.099,
    dlat: 38.7974,
    dlng: -9.3905,
    classId: "vc_premium",
    basePrice: 6800,
  },
  {
    pickup: "Hotel Avenida Palace, Lisboa",
    dropoff: "Belém Tower, Lisboa",
    plat: 38.7155,
    plng: -9.142,
    dlat: 38.6916,
    dlng: -9.216,
    classId: "vc_comfort",
    basePrice: 2800,
  },
  {
    pickup: "Chiado, Lisboa",
    dropoff: "Aeroporto de Lisboa (LIS), Lisboa",
    plat: 38.7108,
    plng: -9.1427,
    dlat: 38.7756,
    dlng: -9.1354,
    classId: "vc_premium",
    basePrice: 3800,
  },
  {
    pickup: "Aeroporto de Faro (FAO), Faro",
    dropoff: "Marina de Lagos, Lagos",
    plat: 37.0144,
    plng: -7.9659,
    dlat: 37.1014,
    dlng: -8.6744,
    classId: "vc_van",
    basePrice: 12500,
  },
  {
    pickup: "Porto Airport (OPO), Porto",
    dropoff: "Ribeira, Porto",
    plat: 41.2421,
    plng: -8.6785,
    dlat: 41.1405,
    dlng: -8.613,
    classId: "vc_comfort",
    basePrice: 3500,
  },
  {
    pickup: "Santa Apolónia, Lisboa",
    dropoff: "Parque das Nações, Lisboa",
    plat: 38.7139,
    plng: -9.122,
    dlat: 38.7681,
    dlng: -9.097,
    classId: "vc_comfort",
    basePrice: 2200,
  },
  {
    pickup: "Four Seasons Ritz, Lisboa",
    dropoff: "Estoril Casino, Estoril",
    plat: 38.7255,
    plng: -9.154,
    dlat: 38.705,
    dlng: -9.397,
    classId: "vc_premium",
    basePrice: 7200,
  },
  {
    pickup: "Cais do Sodré, Lisboa",
    dropoff: "Costa da Caparica, Almada",
    plat: 38.706,
    plng: -9.145,
    dlat: 38.644,
    dlng: -9.235,
    classId: "vc_van",
    basePrice: 4500,
  },
];

export const REVIEW_COMMENTS = [
  "Punctual, immaculate car, calm drive.",
  "Excellent meet-and-greet at arrivals.",
  "Professional and friendly — will book again.",
  "Spotless vehicle and helpful with luggage.",
  "Smooth ride, great communication.",
  "On time despite traffic. Highly recommended.",
  "Quiet cabin, perfect for a business trip.",
  "Driver tracked the flight and waited patiently.",
  "Clean, comfortable, fair price.",
  "Five stars — felt safe the whole way.",
];

export const DOC_TYPES = [
  "IDENTITY",
  "DRIVING_LICENSE",
  "VEHICLE_REGISTRATION",
  "INSURANCE",
  "PROFILE_PHOTO",
] as const;
